Centreon\Application\Request\AckRequest:
    properties:
        acknowledgement:
            type: Centreon\Domain\Acknowledgement\Acknowledgement
            groups:
                - 'bulk_acknowledge'
        resources:
            type: array<Centreon\Domain\Monitoring\MonitoringResource>
            groups:
                - 'bulk_acknowledge'
